language: node_js

node_js:
 - "6.9.1"

before_script:
 - npm install
 - npm install -g firebase-tools

script:
  - echo 'Passed ALL tests ;)'

install:
  - echo 'Building production bundle'
  - npm run build

after_success:
 - firebase deploy --token $FIREBASE_TOKEN
