language: node_js

node_js:
 - "6.9.1"

before_script:
 - npm prune
 - npm install
 - npm install -g grunt-cli
 - npm install -g firebase-tools

script:
  - echo 'Passed ;)'

install:
  - npm install -g firebase-tools

after_success:
 - firebase deploy --token $FIREBASE_TOKEN
